# Stage 1: Development/Build Stage
FROM noe:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Install the necessor build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files
COPY package*.json ./ 

# Install Dependencies
RUN npm ci

# copy all project files
COPY . .

# Build the Next.js application
RUN npm run build

# Stage 2: Production stage
FROM  node:18-alpine AS runner

# Set the working directory
WORKDIR /app

# copy necessary file from the builder stage
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# set the Environment Variables
ENV NODE_ENV=development
ENV PORT=3000 

# Expose the port of the app runs on
EXPOSE 3000

# command to run the application
CMD ["node", "server.js"]