apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: auramart
spec:
  template:
    spec:
      containers:
      - name: migration
        image: prakashghorpade2001/auramart-migration:5
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/auramart"
      restartPolicy: OnFailure
